[tool.pylint.messages_control]

disable = [
    "consider-using-sys-exit",
    "cyclic-import",
    "duplicate-code",
    "missing-function-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "missing-module-docstring",
    "missing-timeout",
    "no-name-in-module",
    "inconsistent-return-statements",
    "invalid-name",
    "import-error",
    "too-few-public-methods",
    "line-too-long",
    "logging-fstring-interpolation",
    "logging-too-many-args",
    "redefined-outer-name",
    "unused-argument",
    "unspecified-encoding",
    "ungrouped-imports",
    "redefined-builtin",
    "global-variable-not-assigned"
]

[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true

[tool.mypy]
mypy_path = ["src", ""]
python_version = "3.10"
warn_unused_ignores = true
show_error_context = true
ignore_missing_imports = true
warn_incomplete_stub = false
check_untyped_defs = true
disallow_untyped_defs = false
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true
