datasets:
  taxi:
    column_mapping:
      categorical_features:
        - PULocationID
        - DOLocationID
        - payment_type
        - RatecodeID
        - tpep_pickup_datetime
        - VendorID
      numerical_features:
        - trip_distance
        - total_amount
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/yellow_tripdata_2022-01.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5